services:
  - type: web
    name: tron-risk
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: bash -lc "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: SNAPSHOT_TTL_MINUTES
        value: "120"
      - key: SNAPSHOT_DIR
        value: "/tmp/tron_risk_snapshots"
      - key: TRONSCAN_API_KEY
        sync: false
      - key: HOST
        value: "0.0.0.0"
      - key: PORT
        value: "8000"
